### ISSUE TITLE
How I can add cache header?

### ISSUE THREAD

**Issue by dannluciano** [victor-o-silva/db_file_storage#103]
Exists any feature to enable cache header in response? 
You accept pull request for this?

**Comment by victor-o-silva** [comment]
I've added a new feature in version 0.5.5, take a look: https://django-db-file-storage.readthedocs.io/en/stable/#customizing-http-headers

Does that work for you?

**Comment by dannluciano** [comment]
I try this 
``` python
path('files/get/', db_file_storage_views.get_file, 
        {
            'add_attachment_headers': False,
            'extra_headers': {'Cache-Control': 'public, max-age=31536000'}
        },
        name='db_file_storage.get_file'),
```
In response header a see the cache-control header but when a refresh the page the server send a response with status 200 and not 304.

**Comment by victor-o-silva** [comment]
@dannluciano 
AFAIK, when the server sends a `Cache-Control` header, the responsibility of caching the response falls on the client. The browser (or whatever your client is) should handle this.

In the example below, I changed the URLs of the demo project like this:

```
    url(
        r'^book-cover-view/',
        db_file_storage_views.get_file,
        {
            'add_attachment_headers': False,
            'extra_headers': {'Cache-Control': 'public, max-age=31536000'}
        },
        name='book.view_cover'
    ),
```

And I changed the books list template to use the new URL:

```
<img height=64 width=64 src="{% url 'model_files:book.view_cover' %}?name={{ obj.cover }}" />
```

As you can see in the screenshot below, Google Chrome handles the caching process: after fetching the image once, it was stored in the browser's cache and it was not requested again from the server.

![Screenshot from 2020-06-02 21-07-24](https://user-images.githubusercontent.com/3804282/83582026-c0290a00-a516-11ea-97cc-b8bed8375d0c.png)

**Comment by dannluciano** [comment]
Nice. In Firefox when I reload the page with 'F5' the images sent by whitenoise return 304 and images sent by db_file_storage returns 200. But when I reload the same page with a link the images sent by db_file_storage return 200 but with cached value.

Thanks for your answers.

**Comment by victor-o-silva** [comment]
No problem

Whitenoise may be using the [ETag header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)
