### ISSUE TITLE
add db_file_storage to file_storage in Form wizard

### ISSUE THREAD

**Issue by rid3r77** [victor-o-silva/db_file_storage#14]
Is there a way to get it work with Form wizards ?, I just added in my Form wizard class as:
 file_storage = DatabaseFileStorage() 

It raised this error:
list index out of range
The exception came from the method exists at line 104 in storage.py 

I thought it was because I have to add the prefix like in upload_to: app_name/class/bytes/filename/mimetype, but I didn't know how to get it work.

If this issue doesn't go here, please drop it.
Thanks in advance.

**Comment by victor-o-silva** [comment]
Hi!
`db_file_storage` doesn't work with Form Wizards yet.
Thanks for the report! I am working on that for the next release.

**Comment by rid3r77** [comment]
@victor-o-silva 
Thanks in advance. 
Regards.

**Comment by victor-o-silva** [comment]
closed by #15 

@rid3r77 , now there is a class suitable for use in Form Wizards.
It's on the version 0.3.1 of the library, already on PyPI.
There is a [section in the docs](https://github.com/victor-o-silva/db_file_storage/blob/master/README.rst#how-to-use-for-form-wizards) for this new functionality.
