### ISSUE TITLE
Transfer to Jazzband?

### ISSUE THREAD

**Issue by iamjameswalters** [victor-o-silva/db_file_storage#174]
It looks like this project has had a few pull requests opened over the last couple of years, but they haven't been looked at. If maintenance is a burden, have you considered transferring this project over to [Jazzband](https://jazzband.co/)?

**Comment by konnerdave** [comment]
I also agree. This project needs to atleast support Django 4.2 soon.

**Comment by Aagam41** [comment]
Hi,
I wanted to inform you that I have taken ownership of the project and will be actively maintaining it moving forward. I appreciate your consideration in suggesting the Jazzband transfer, but I am committed to ensuring the continued development and improvement of the project.

If you have any specific concerns or questions regarding the transition or future development plans, feel free to reach out. I'm more than happy to discuss any aspects of the project with you.
