### ISSUE TITLE
When can we expect a release supporting Django 4.2?

### ISSUE THREAD

**Issue by konnerdave** [victor-o-silva/db_file_storage#199]
Since there is no other way to contact @Aagam41. I'm opening this issue to ask when can we expect a new release supporting the newer version of Django?

**Comment by Aagam41** [comment]
Hello there,

I appreciate your interest in the upcoming release! I'm pleased to inform you that I have **_already pushed the necessary code changes to support Django 4.x_** and above, including the latest version, Django 5.x. Currently, I am in the **testing phase** to ensure everything functions seamlessly.

Anticipating the completion of testing and debugging, I plan to make the **new release** within the **next two days**. Thank you for your patience, and feel free to reach out if you have any further questions or concerns.

Best regards,
Aagam Sheth

**Comment by konnerdave** [comment]
@Aagam41 Any updates on the release?

**Comment by Aagam41** [comment]
@konnerdave Released the updates on pypi [django-db-file-storage](https://pypi.org/project/django-db-file-storage/). Please check now.

**Comment by konnerdave** [comment]
@Aagam41 Thanks for the update. Although it has a weird version numbering.
