### ISSUE TITLE
mimetype

### ISSUE THREAD

**Issue by acer9997** [victor-o-silva/db_file_storage#2]
I think on line 60, ```mimetype = content.file.content_type``` should be ```mimetype = content.content_type```.

**Comment by victor-o-silva** [comment]
I tested with django 1.4 and 1.7 and it is working fine with `content.file.content_type`.
Please add more details if it's not working properly for you.
And I hadn't seen this issue until now, sorry for the giant delay.

**Comment by pwhipp** [comment]
I've just upgraded from Django 1.6 to 1.7 and a test in our application is failing with "AttributeError: '_io.BytesIO' object has no attribute 'content_type'":

```
    def test_should_accept_file(self):
        file_name = 'file.txt'
        self.ip_file.metadata.save(file_name, ContentFile('Test for upload'))
        self.assertTrue(self.ip_file.metadata.file)
```
ip_file:
```
class IPFile(CommonModel):
   ...
    metadata = models.FileField(upload_to='ips.FileHolder/bytes/filename/mimetype',
                                null=True,
                                blank=True,
                                verbose_name=u'IP Metadata File',
                                storage=DatabaseFileStorage())
```

FileHolder:
```
class FileHolder(models.Model):
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)
```

I'm not sure if this is related to this closed issue but any insight would be appreciated.
