### ISSUE TITLE
Invalid request when hosted on Windows

### ISSUE THREAD

**Issue by aaronstephenson** [victor-o-silva/db_file_storage#24]
This module works great on my Linux dev box, but not on my Windows dev box. I am able to upload a file successfully (through the Admin app), but a GET request (or clicking the file download link in the Admin app) returns a 400 error with the message "Invalid request". I think the problem lies with the different path separators in the file name (back slash in Windows, forward slash in Linux), because when I change the direction of the path separators in the file name to back slashes in my GET requests on my Windows dev box, the file downloads perfectly:

this fails:
curl -X GET http://localhost:8000/files/download/?name=myapp.DatabaseFile/bytes/filename/mimetype/test.png

this works:
curl -X GET http://localhost:8000/files/download/?name=myapp.DatabaseFile\bytes\filename\mimetype\test.png

**Comment by victor-o-silva** [comment]
Thank you for the report.

First of all, sorry for taking so long to address this. There was a Pull Request with part of the fix but I didn't have access to a Windows machine for a long time.

Version [0.4.1](https://github.com/victor-o-silva/db_file_storage/releases/tag/0.4.1) (already on [PyPI](https://pypi.python.org/pypi/django-db-file-storage/0.4.1)) doesn't have the reported problem anymore.

Thanks again!
