### ISSUE TITLE
ImportError: cannot import name FileWrapper

### ISSUE THREAD

**Issue by acer9997** [victor-o-silva/db_file_storage#26]
With Django 1.9, getting error "db_file_storage/views.py", line 2, in <module> from django.core.servers.basehttp import FileWrapper ImportError: cannot import name FileWrapper".

Should line 2 be replaced with "from wsgiref.util import FileWrapper"?

**Comment by sglebs** [comment]
I am having the same problem. I see that other libraries are too. See: https://github.com/groveco/django-sql-explorer/issues/137

**Comment by victor-o-silva** [comment]
Fixed by [20f7081](https://github.com/victor-o-silva/db_file_storage/commit/20f70816f50a371be825c5d5528db8a0c1853b61)
Already on [PyPI (version 0.4.0)](https://pypi.python.org/pypi/django-db-file-storage/0.4.0)
Thanks, guys!
