### ISSUE TITLE
delete_file_if_needed should use instance.pk instead of instance.id

### ISSUE THREAD

**Issue by lbjworld** [victor-o-silva/db_file_storage#31]
when using delete_file_if_needed to remove file, I got error as follows:
`AttributeError: 'MyModel' object has no attribute 'id'`

because I customized my model's primary_key name.

**Comment by victor-o-silva** [comment]
Thank you for the report! =)

Fixed by 0089b12423
Already available at [Pypi (0.4.2)](https://pypi.python.org/pypi/django-db-file-storage)
