### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by aleyan** [victor-o-silva/db_file_storage#39]
Is there planned support for Django 1.11 or should I try working on it myself?

Currently running the tests with Django 1.11.7 results with 3 failures. `test_admin_form_widget_shows_proper_filename`, `test_binary_file`, and `test_form_widget_shows_proper_filename`.

**Comment by victor-o-silva** [comment]
Yes, I will work on 1.11 support this weekend, and hopefully I'll get it done quickly!

**Comment by victor-o-silva** [comment]
Thanks for the report, @aleyan 

Fixed in 0fd82c2..62c2835
Available on [PyPI (0.4.4)](https://pypi.python.org/pypi/django-db-file-storage)

**Comment by aleyan** [comment]
Thank you so much. I will let you know if I discover any issues.
