### ISSUE TITLE
Templates are missing in 0.4.4 PyPI Package

### ISSUE THREAD

**Issue by mbrunthaler** [victor-o-silva/db_file_storage#40]
Templates are not bundled with current release.

**Comment by victor-o-silva** [comment]
Thanks for the report, @mbrunthaler .
I'll fix this tonight.

**Comment by victor-o-silva** [comment]
Fixed in [v0.4.5 ](https://github.com/victor-o-silva/db_file_storage/releases/tag/0.4.5).
Already [on PyPI](https://pypi.python.org/pypi/django-db-file-storage/).

Thanks again!
