### ISSUE TITLE
Library doesn't seem to work with django's ContentFile class

### ISSUE THREAD

**Issue by victor-o-silva** [victor-o-silva/db_file_storage#5]
Library doesn't seem to work with [django's ContentFile class](https://docs.djangoproject.com/en/1.7/ref/files/file/#the-contentfile-class), as described by @pwhipp on issue #2.

**Comment by victor-o-silva** [comment]
Actually, the library wasn't working when out of the ModelForm standard cycle: it was failing when the files were being saved manually. Fixed in b7158175ae31cc7d71743ee59163beaf62e784f0.

**Comment by pwhipp** [comment]
Thanks for addressing this so quickly. We'll be integrating the new version shortly.
