### ISSUE TITLE
TemplateDoesNotExist - db_file_storage/widgets/admin_clearable_file_input.html

### ISSUE THREAD

**Issue by BeanJiu** [victor-o-silva/db_file_storage#56]
Hello,
I am facing an issue, I keep having the error TemplateDoesNotExist - db_file_storage/widgets/admin_clearable_file_input.html when I package my app.
I use other third party apps, no issue, all templates, static are collected and there, but for some reason not for db_file_storage. The app is properly referenced in INSTALLED_APPS

`Django tried loading these templates, in this order:

Using engine django:

    django.template.loaders.filesystem.Loader: /Users/toto/.pex/install/Django-2.0.2-py3.6.egg.0a9fb7bc8d9dbc7082915e607b8e4ee0e96686d2/Django-2.0.2-py3.6.egg/django/forms/templates/db_file_storage/widgets/admin_clearable_file_input.html (Source does not exist)`

Django-2.0.2, 
Python Version:  3.6.0
django-db-file-storage==0.5.1

any idea where it can come from ? thx

**Comment by victor-o-silva** [comment]
Thanks for the report, @BeanJiu .

I **think** that this has to do with db_file_storage's `MANIFEST.in` file.
I have [made a change](https://github.com/victor-o-silva/db_file_storage/commit/aa2bcacc2c28272af740f54922504e93a98e26d8) to it and uploaded a [new version to PyPI](https://pypi.python.org/pypi/django-db-file-storage/0.5.2).

Can you tell me if the packaging works with `django-db-file-storage==0.5.2`, please?

**Comment by victor-o-silva** [comment]
@BeanJiu 
Feel free to reopen this if needed
