### ISSUE TITLE
Configurable field type for content

### ISSUE THREAD

**Issue by tovmeod** [victor-o-silva/db_file_storage#64]
Currently the file contents are stored in a TextField

I would like to store it in a bytea when using postgres.

Django has a BinaryField type (https://docs.djangoproject.com/en/2.1/ref/models/fields/#binaryfield)

Which should translate to bytea and the correct blob type for each database.

I believe this kind of behaviour could be configurable

**Comment by victor-o-silva** [comment]
Thanks, @tovmeod . That's a nice suggestion.

**Comment by victor-o-silva** [comment]
[Version 0.5.3](https://pypi.org/project/django-db-file-storage/0.5.3/), uploaded to PyPI, with support for django's `BinaryField`.
